name: Build project check

on:
    push:
        branches:
            - main
    workflow_dispatch: {}

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Install Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: "16"

            - name: Checkout war3js_unsafe repository
              uses: actions/checkout@v4
              with:
                  repository: kirill-782/war3js_unsafe
                  path: unsafe

            - name: Install unsafe dependencies
              run: npm install
              working-directory: ./unsafe

            - name: Build unsafe
              run: npm run build
              working-directory: ./unsafe

            - name: Checkout current repository
              uses: actions/checkout@v4
              with:
                  path: bootstrap

            - name: Install dependencies
              run: npm install
              working-directory: ./bootstrap

            - name: Bundle js file
              run: npm run bundle
              working-directory: ./bootstrap

            - name: Bundle types
              run: npm run typesgen
              working-directory: ./bootstrap

            - name: Upload bootstrap.js
              uses: actions/upload-artifact@v3
              with:
                  name: bootstrap.js
                  path: ./bootstrap/build/esbuild/bootstrap.js

            - name: Upload natives.d.ts
              uses: actions/upload-artifact@v3
              with:
                  name: natives.d.ts
                  path: ./bootstrap/build/fullTypes/natives.d.ts

            - name: Upload constants.d.ts
              uses: actions/upload-artifact@v3
              with:
                  name: constants.d.ts
                  path: ./bootstrap/build/fullTypes/constants.d.ts

            - name: Upload bootstrap.d.ts
              uses: actions/upload-artifact@v3
              with:
                  name: bootstrap.d.ts
                  path: ./bootstrap/build/fullTypes/bootstrap.d.ts
